### ISSUE TITLE
Change game name

### ISSUE THREAD

**Issue by Jan130** [Xinoi/SpaceGame#11]
### Discussed in https://github.com/Xinoi/SpaceGame/discussions/10

<div type='discussions-op-text'>

<sup>Originally posted by **itsSanoi** May  9, 2022</sup>
Suggestions?</div>

**Comment by Jan130** [comment]
Current idea: "Definitely not a Space Invaders Clone" or DNASIC

**Comment by itsSanoi** [comment]
Personaly i think thats a good option

**Comment by Xinoi** [comment]
ok i already implemented it like this in the Menu Screen branch on which im currently working

**Comment by Jan130** [comment]
I'm going to adapt the package and class names to fit the new name once the Menu branch is merged

**Comment by Xinoi** [comment]
Ok then its D N A S I C
